### PR TITLE
Fix: Don't rely on shape of `_readableState`

### LINKED ISSUE #5: TypeError in _getString() due to change in Node.js Buffer.concat()
Stack trace:

```
Failures:
    TypeError: "list" argument must be an Array of Buffers
        at Function.Buffer.concat (buffer.js:313:11)
        at MockExpressResponse.MockServerResponse._getString (/home/travis/build/oddnetworks/oddworks/node_modules/mock-res/index.js:55:16)
        at MockExpressResponse.MockServerResponse._getJSON (/home/travis/build/oddnetworks/oddworks/node_modules/mock-res/index.js:59:25)
```

Not sure exactly what changed, but I'm going to monkey patch this locally and see what happens.

### PR DESCRIPTION
**Pull request by justmoon**
The previous code relies on the shape of the private property `_readableState` which caused it to break for more recent versions of Node.js. This patch changes the implementation to use the public, documented interface only.

Fixes #5.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -52,7 +55,7 @@ MockServerResponse.prototype.writeHead = function(statusCode, reason, headers) {
 };
 
 MockServerResponse.prototype._getString = function() {
-	return Buffer.concat(this._readableState.buffer).toString();
```
Comment (ThaNarie) [inline index.js]: @diachedelic I see this has been merged already, but it seems to `.toString()` was removed by accident.

When I apply these changes in my node_modules version (`0.2.1` installed via `mock-express-response`) I get this as a result:
`<Buffer 3c 21 44 4f 43 54 59 50 ... >`

When adding the `.toString();` I'm getting the correct string result.
